---
title: "Figure2_part1"
author: "Jiang junyao"

output: 
  prettydoc::html_pretty:
    toc: true
    theme: cayman
    highlight: github
---
Here is the script to generate figures in Figure 2 and related supplementary figures in the PolyATAC manuscript.

## Load data
```{r}
library(tidyverse)
library(ggpubr)
library(pheatmap)
library(BuenColors)
source('/data/jiangjunyao/polyATAC/github_script/help_function/figure2_help_function.R')
celltype_color <- read.csv("/data/jiangjunyao/polyATAC/color_gcy.csv",header = F)
celltype_color$V2 = gsub(' ','',celltype_color$V2)
metadata = read.csv('/data/jiangjunyao/polyATAC/github_script/data/metadata_1125.csv',
                    row.names = 1)
heatmap_col = c('#F7FBFF','#DEEBF7','#C6DBEF','#9ECAE1','#6BAED6','#4292C6',
                  '#2171B5','#08519C','#08306B')
germ_col = c('#98DF8AFF',
             '#DBDB8DFF',
             '#AEC7E8FF',
             '#C5B0D5FF',
             '#FFBB78FF')
germ = c('NeuroEctoderm','SurfaceEctoderm','Mesoderm',
         'Endoderm','Extraembryonic')
```

## Plot cell embedding

```{r}
ggplot(metadata,aes(x=umap1,y=umap2,color=celltype))+geom_point(size=0.1)+
  scale_color_manual(values=celltype_color$V2,breaks = celltype_color$V1)+
  theme_void()+theme(text = element_text(size=15))+theme(legend.position = "none")
ggsave('/data/jiangjunyao/polyATAC/polyatac_figure/all_embedding_no_legend/fig2/fig2_celltype.pdf',
       width = 10,height = 8)
ggplot(metadata,aes(x=umap1,y=umap2,color=neuron_only))+geom_point(size=0.1)+
  scale_color_manual(values=celltype_color$V2,breaks = celltype_color$V1)+
  theme_void()+theme(text = element_text(size=15))+theme(legend.position = "none")
ggsave('/data/jiangjunyao/polyATAC/polyatac_figure/all_embedding_no_legend/fig2/fig2_neuron_only.pdf',
       width = 10,height = 8)
germ_col = c('#98DF8AFF',
             '#DBDB8DFF',
             '#AEC7E8FF',
             '#C5B0D5FF',
             '#FFBB78FF')
germ = c('NeuroEctoderm','SurfaceEctoderm','Mesoderm',
         'Endoderm','Extraembryonic')
ggplot(metadata,aes(x=umap1,y=umap2,color=germ))+geom_point(size=0.1)+
  scale_color_manual(values=germ_col,breaks = germ)+
  theme_void()+theme(text = element_text(size=15))+theme(legend.position = "none")
ggsave('/data/jiangjunyao/polyATAC/polyatac_figure/all_embedding_no_legend/fig2/fig2_germ.pdf',
       width = 10,height = 8)

ggplot(metadata,aes(x=umap1,y=umap2,color=time))+geom_point(size=0.1)+
  theme_void()+theme(text = element_text(size=15))+
  scale_color_manual(values = jdb_palette('brewer_spectra'))
ggsave('/data/jiangjunyao/polyATAC/polyatac_figure/all_embedding_no_legend/fig2/fig2_time.pdf',
       width = 10,height = 8)
ggplot(metadata,aes(x=umap1,y=umap2,color=detection))+geom_point(size=0.1)+
  theme_void()+theme(text = element_text(size=15))+
  scale_color_manual(values = c('#a7324a','grey'))+NoLegend()
ggsave('/data/jiangjunyao/polyATAC/polyatac_figure/all_embedding_no_legend/fig2/fig2_detection.pdf',
       width = 10,height = 8)
# plot_time_emb2 <-function(meta,time1,col1='time'){
#   meta$x = meta$umap1
#   meta$y = meta$umap2
#   meta$use_col = meta[,col1]
#   meta_plot1 = meta[meta[,col1]!=time1,]
#   meta_plot1$use_col='ohter'
#   meta_plot2 = meta[meta[,col1]==time1,]
#   meta$use_col = meta
#   ggplot(meta_plot1,aes(x=x,y=y,color=use_col))+geom_point(size=0.1)+
#     scale_color_manual(values = c('grey','#a7324a'))+theme_void()+
#     geom_point(data=meta_plot2,aes(x=x,y=y,color=use_col),size=0.2)+theme(legend.position = "none")
# }
# plot_time_emb2(metadata,'with barcode','detection')
# ggsave('/data/jiangjunyao/polyATAC/polyatac_figure/all_embedding_no_legend/fig2/fig2_detection.pdf',
#        width = 10,height = 8)
```

### Pgen
```{r}
fatebias=c('Endoderm-bias'='#C5B0D5FF',
                              'Mesoderm-bias'='#AEC7E8FF',
                              'NeuroEctoderm-bias'='#98DF8AFF',
                              'SurfaceEctoderm-bias'='#DBDB8DFF',
                              "Extraembryonic-bias"='#FFBB78FF',
                              'Multilineage'=rgb(242/255,150/255,155/255))
group_df = readRDS('/data/jiangjunyao/polyATAC/all_barcode_kmeans_V2.rds')
list1 = list()
for (i in c(0.001,0.0001,0.00001)) {
  group_df_use = group_df[group_df$pgen<i,]
  df1 = as.data.frame(table(group_df_use$fate))
  df1$ratio = df1[,2]/sum(df1[,2])
  df1$pgen = as.character(i)
  list1[[as.character(i)]] = df1
}
df_ratio = do.call(bind_rows,list1)
ggplot(df_ratio,aes(x=pgen,y=ratio,fill=Var1))+geom_col()+
  scale_fill_manual(values = fatebias)+theme_classic()+
  scale_y_continuous(expand = c(0,0))+theme(text = element_text(size=16))
ggsave('/data/jiangjunyao/polyATAC/polyatac_figure/single cell fig/cell type statistic and fraction plot/Pgen_fate_fraction.pdf',width = 10,height = 8)
```

### E8.5 repeats
```{r}
celltype_sample_fraction <- function(scvi_meta,sample='orig.ident',
                                     celltype='celltype'){
  library(BuenColors)
  library(ggplot2)
  library(Seurat)
  ct_freq_list = list()
  for (i in unique(scvi_meta[,sample])) {
    print(i)
    meta_use = scvi_meta[scvi_meta[,sample]==i,]
    df1 = as.data.frame(table(meta_use[,celltype]))
    colnames(df1) = c('celltype','number')
    df1$sample = i
    df1$number = (df1$number/sum(df1$number))*100
    ct_freq_list[[i]] = df1
  }

  ct_freq_df = do.call(bind_rows,ct_freq_list)
  ct_freq_df = ct_freq_df[,c(1,3,2)]
  ct_freq_df2 = reshape2::dcast(ct_freq_df,formula = celltype~sample)
  p1 = ggplot(ct_freq_df,aes(x=sample,y=number,fill=celltype))+geom_col() + theme_classic() +
    scale_fill_manual(values=celltype_color$V2,breaks = celltype_color$V1)+
    guides(color = guide_legend(override.aes = list(size = 4)))+theme(text=element_text(size=15))+
    xlab('')+scale_y_continuous(expand = c(0,0))+ylab('ratio(%)')+
    theme(axis.text.x = element_text(vjust = 0.5, hjust = 0.5,
                                     angle = 35))
  print(p1)
  return(ct_freq_df2)
}
e85_1 = metadata[metadata$Batch %in% c('E8.5-Embryo1-Repeats1',
                                       'E8.5-Embryo1-Repeats2'),]
e85_2 = metadata[metadata$Batch %in% c('E8.5-Embryo2-Repeats1',
                                       'E8.5-Embryo2-Repeats2'),]
celltype_sample_fraction(e85_1,'Batch','celltype')
ggsave('/data/jiangjunyao/polyATAC/polyatac_figure/single cell fig/cell type statistic and fraction plot/E85_mouse1_repeat_celltype_fraction.pdf',width = 10,height = 8)
celltype_sample_fraction(e85_2,'Batch','celltype')
ggsave('/data/jiangjunyao/polyATAC/polyatac_figure/single cell fig/cell type statistic and fraction plot/E85_mouse2_repeat_celltype_fraction.pdf',width = 10,height = 8)
```

### clone size analysis
```{r}
size_df=as.data.frame(table(group_df$size))
size_df[,1] = as.numeric(size_df[,1])
ggplot(size_df,aes(x=Var1,y=Freq))+geom_col()+theme_minimal()+
  theme(text = element_text(size=18))+xlab('clone size (cell number)')+ylab('clone number')+scale_y_log10()
ggsave('/data/jiangjunyao/polyATAC/polyatac_figure/single cell fig/cell type statistic and fraction plot/clone_size_frequency.pdf',width = 10,height = 8)
group_df = group_df[order(group_df$size,decreasing = T),]
group_df$id = 1:nrow(group_df)
ggplot(group_df,aes(x=id,y=size))+geom_point(size=0.4)+theme_classic()+scale_x_continuous(labels = NULL)+
  theme(text = element_text(size=18))+xlab('clone ID')+ylab('clone size (cell number)')
ggsave('/data/jiangjunyao/polyATAC/polyatac_figure/single cell fig/cell type statistic and fraction plot/all_clone_size.pdf',width = 10,height = 8)


group_df = group_df[!is.na(group_df$mouse),]
group_df[group_df$fate=='Endoderm-restricted','fate'] = 'Endoderm-bias'
group_df[group_df$fate=='Mesoderm-restricted','fate'] = 'Mesoderm-bias'
group_df[group_df$fate=='NeuroEctoderm-restricted','fate'] = 'NeuroEctoderm-bias'
group_df[group_df$fate=='SurfaceEctoderm-restricted','fate'] = 'SurfaceEctoderm-bias'
group_df$type = '3.1< clone size <20'
group_df$type[group_df$size>20] = '2.20 < clone szie < 40'
group_df$type[group_df$size>40] = '1.clone szie > 40'
group_df$type[group_df$size==1] = '4.clone szie =1'
ggplot(group_df,aes(y=fate,x=size,fill=type))+geom_col()+theme_minimal()+
  theme(text = element_text(size=15))+xlab('cell number')+scale_fill_manual(values = jdb_palette('corona'))
ggsave('/data/jiangjunyao/polyATAC/polyatac_figure/single cell fig/cell type statistic and fraction plot/clone_size_range.pdf',width = 12,height = 6)
group_df$clone_id = 1
ggplot(group_df,aes(y=fate,x=clone_id,fill=type))+geom_col()+theme_minimal()+
  theme(text = element_text(size=15))+xlab('clone number')+scale_fill_manual(values = jdb_palette('corona'))
ggsave('/data/jiangjunyao/polyATAC/polyatac_figure/single cell fig/cell type statistic and fraction plot/clone_number_range.pdf',width = 12,height = 6)

```


### germ-layer lineage tree
```{r}
coup = read.csv('/data/jiangjunyao/polyATAC/germ_lineage/all_germ_coup.csv',row.names = 1)
max_val = max(coup[coup<0.99])
coup[coup>0.99] = max_val
pheatmap(coup,clustering_method = 'single',color = colorRampPalette(heatmap_col)(50),border_color = NA,filename = '/data/jiangjunyao/polyATAC/polyatac_figure/single cell fig/germ_tree/all_time_heatmap.pdf',width = 10,height = 8)

```

### CNS lineage tree
```{r}
dir1 = dir('/data/jiangjunyao/polyATAC/subcelltype_coupling/CNS_time')
dir1 = dir1[grep('coupling',dir1)]
list1 = list()
for (i in dir1[-1]) {
  coup = read.csv(paste0('/data/jiangjunyao/polyATAC/subcelltype_coupling/CNS_time/',i),row.names = 1)
  max_val = max(coup[coup<0.99])
  coup[coup>0.99] = max_val
  i = gsub('_coupling.csv','',i)
  list1[[i]] = coup
  pheatmap(coup,clustering_method = 'mcquitty',color = colorRampPalette(heatmap_col)(50),border_color = NA,filename = paste0('/data/jiangjunyao/polyATAC/polyatac_figure/single cell fig/subcluster lineage analysis/CNS_',i,'_heatmap.pdf'),width = 10,height = 8)
}

similarity_score_df = data.frame(c(0.12500758,0.13405239,0.10609600,0.080628957,0.08080803,0.12763031),
                    c(8.5,9,9.5,8.5,9,9.5),c(rep('Spinal cord-Hindbrain',3),rep('Di/telencephalon-Mesencephalon/MHB',3)))
colnames(similarity_score_df) = c('lineage_similarity','time','celltype_pair')
ggplot(similarity_score_df,aes(x=time,y=lineage_similarity,color=celltype_pair))+geom_line(size=1)+
  ylim(0, 0.15)+theme_minimal()+scale_color_manual(values = jdb_palette('brewer_spectra')[c(1,3)])+
  theme(text = element_text(size=16))
ggsave('/data/jiangjunyao/polyATAC/polyatac_figure/single cell fig/subcluster lineage analysis/CNS_lineage_similarity_summary.pdf',width = 10,height = 8)
```

### CNS lineage tree
```{r}
dir1 = dir('/data/jiangjunyao/polyATAC/subcelltype_coupling/CNS_time')
dir1 = dir1[-grep('coupling',dir1)]
list1 = list()
for (i in dir1) {
  coup = read.csv(paste0('/data/jiangjunyao/polyATAC/subcelltype_coupling/CNS_time/',i),row.names = 1)
  coup = t(apply(coup, 1, function(x){
        row_sum = sum(x)
        return(x/row_sum)
    }))
pheatmap(coup,clustering_method = 'mcquitty',color = colorRampPalette(heatmap_col)(50),show_rownames = F,border_color = NA,filename = paste0('/data/jiangjunyao/polyATAC/polyatac_figure/single cell fig/subcluster lineage analysis/CNS_',i,'_fateoutcome.pdf'),width = 10,height = 8)
}

```
